# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:07
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20171125_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
